// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFecHzpcDXl4lYaneKqei58agcllFFfM',
    appId: '1:341307600695:web:c7e79b41661ac0b732b4b2',
    messagingSenderId: '341307600695',
    projectId: 'liver-cancer-detection',
    authDomain: 'liver-cancer-detection.firebaseapp.com',
    storageBucket: 'liver-cancer-detection.appspot.com',
    measurementId: 'G-HGQE2B5QN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SYf3hh9faMORMA7y-_cv_FgwEyzodPE',
    appId: '1:341307600695:android:6b6b55c9f9801f5332b4b2',
    messagingSenderId: '341307600695',
    projectId: 'liver-cancer-detection',
    storageBucket: 'liver-cancer-detection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-CwK5Ye08qWeRzsCmTot1CYCWC4Vyk8',
    appId: '1:341307600695:ios:9a74f49b4e89e30332b4b2',
    messagingSenderId: '341307600695',
    projectId: 'liver-cancer-detection',
    storageBucket: 'liver-cancer-detection.appspot.com',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-CwK5Ye08qWeRzsCmTot1CYCWC4Vyk8',
    appId: '1:341307600695:ios:9a74f49b4e89e30332b4b2',
    messagingSenderId: '341307600695',
    projectId: 'liver-cancer-detection',
    storageBucket: 'liver-cancer-detection.appspot.com',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwFecHzpcDXl4lYaneKqei58agcllFFfM',
    appId: '1:341307600695:web:fcaec8d393b0c1bf32b4b2',
    messagingSenderId: '341307600695',
    projectId: 'liver-cancer-detection',
    authDomain: 'liver-cancer-detection.firebaseapp.com',
    storageBucket: 'liver-cancer-detection.appspot.com',
    measurementId: 'G-V3SGEJZQD2',
  );
}
